<?php

declare(strict_types=1);

namespace Modules\Core\Support\Forms\TextInputs;

use Closure;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\TextInput\Actions\CopyAction;
use Filament\Support\Enums\Operation;
use Filament\Support\Icons\Heroicon;
use Illuminate\Database\Eloquent\Model;
use Modules\Core\Support\Codes\CodeFormatter;
use Modules\Core\Support\Codes\CodeGenerator;
use RuntimeException;

final class CodeTextInput extends TextInput
{
    protected bool $lockOnEdit = true;

    protected bool $allowManualOnCreate = false;

    protected string|Closure|null $autoModelClass = null;

    protected string|Closure|null $autoPrefix = null;

    protected int|Closure $autoPadding = 3;

    protected bool|Closure $ignoreDeleted = true;

    /**
     * @var array<string, mixed> | Closure
     */
    protected array|Closure $autoScope = [];

    protected function setUp(): void
    {
        parent::setUp();

        $this
            ->prefixIcon(function (string $operation) {
                if ($operation === Operation::Create->value || str($operation)->startsWith('create')) {
                    return Heroicon::Hashtag;
                }
            })
            ->prefixAction(function ($operation) {
                if ($operation === Operation::Create->value || str($operation)->startsWith('create')) {
                    return null;
                }

                return CopyAction::make()
                    ->icon(Heroicon::Hashtag)
                    ->copyMessage(__('Code copied'))
                    ->tooltip(__('Copy code'))
                    ->visible(fn (?string $state): bool => filled($state));
            }, isInline: true)
            ->maxLength(20)
            ->placeholder(__('Autogenerated'))
            ->rule('regex:/^[A-Z0-9_-]+$/')
            ->validationMessages([
                'regex' => __('The code may only contain uppercase letters, numbers, dashes, and underscores.'),
            ])
            ->readOnly()
            ->saved(false)
            ->tenantScopedUnique()
            ->dehydrated()
            ->afterStateHydrated(function (string $operation): void {
                if (! $this->shouldAutoGenerateForOperation($operation) || filled($this->getState())) {
                    return;
                }

                $generated = $this->generateCode($operation);

                if (blank($generated)) {
                    return;
                }

                $this->state($generated);
            })
            ->beforeStateDehydrated(function (string $operation): void {
                if (! $this->shouldAutoGenerateForOperation($operation) || $this->allowManualOnCreate) {
                    return;
                }

                $generated = $this->generateCode($operation);

                if (blank($generated)) {
                    return;
                }

                $this->state($generated);
            }, shouldUpdateValidatedStateAfter: true)
            ->formatStateUsing(fn (?string $state): ?string => CodeFormatter::normalize($state))
            ->dehydrateStateUsing(fn (?string $state): ?string => CodeFormatter::normalize($state));
    }

    public static function getDefaultName(): ?string
    {
        return 'code';
    }

    public function lockOnEdit(bool $condition = true): static
    {
        $this->lockOnEdit = $condition;

        return $this;
    }

    public function tenantScopedUnique(bool|Closure $ignoreRecord = true): static
    {
        $this->scopedUnique(ignoreRecord: $ignoreRecord);

        return $this;
    }

    public function allowManualOnCreate(bool $condition = true): static
    {
        $this->allowManualOnCreate = $condition;

        return $this;
    }

    /**
     * @param  class-string<Model> | Closure  $modelClass
     * @param  array<string, mixed> | Closure  $scope
     */
    public function autoGenerateFromModel(
        string|Closure|null $modelClass = null,
        string|Closure|null $prefix = null,
        int|Closure $padding = 3,
        array|Closure $scope = [],
        bool|Closure $ignoreDeleted = true,
    ): static {
        // Solo guarda los valores, la resolución automática se hace en generateCode()
        $this->autoModelClass = $modelClass;
        $this->autoPrefix = $prefix;
        $this->autoPadding = $padding;
        $this->autoScope = $scope;
        $this->ignoreDeleted = $ignoreDeleted;

        return $this;
    }

    protected function shouldDisableField(string $operation): bool
    {
        if ($operation === 'edit' && $this->lockOnEdit) {
            return true;
        }

        if ($operation === 'create' && $this->shouldAutoGenerateForOperation($operation) && ! $this->allowManualOnCreate) {
            return true;
        }

        return false;
    }

    protected function shouldAutoGenerateForOperation(string $operation): bool
    {
        return $operation === 'create'
            && filled($this->autoModelClass)
            && filled($this->autoPrefix);
    }

    protected function generateCode(string $operation): ?string
    {
        if (! $this->shouldAutoGenerateForOperation($operation)) {
            return null;
        }

        $modelClass = $this->evaluate($this->autoModelClass);
        $prefix = $this->autoPrefix !== null ? (string) $this->evaluate($this->autoPrefix) : null;
        $padding = (int) $this->evaluate($this->autoPadding);
        $scope = $this->evaluate($this->autoScope);
        $ignoreDeleted = (bool) $this->evaluate($this->ignoreDeleted);

        // Si no se definió modelClass, intenta obtenerlo del record
        if (empty($modelClass)) {
            $record = method_exists($this, 'getRecord') ? $this->getRecord() : null;
            if ($record) {
                $modelClass = get_class($record);
            } else {
                throw new RuntimeException(__('Could not automatically resolve modelClass (no record available).'));
            }
        }

        // Si el prefijo es nulo, intenta obtenerlo del modelo
        if ($prefix === null || $prefix === '') {
            if (is_string($modelClass) && class_exists($modelClass) && method_exists($modelClass, 'getCodePrefix')) {
                $prefix = $modelClass::getCodePrefix();
            } else {
                return null;
            }
        }

        if (! is_string($modelClass) || $modelClass === '' || $prefix === '') {
            return null;
        }

        return CodeGenerator::next(
            modelClass: $modelClass,
            prefix: $prefix,
            padding: $padding,
            scope: is_array($scope) ? $scope : [],
        );
    }
}
