<?php

declare(strict_types=1);

namespace Modules\People\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Core\Database\Seeders\Concerns\ReportsSeederProgress;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

final class PermissionsSeeder extends Seeder
{
    use ReportsSeederProgress;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $created = 0;
        $updated = 0;

        $permissions = [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.restore',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'companies.view',
            'companies.create',
            'companies.update',
            'companies.delete',
            'companies.restore',
            'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
            'customers.restore',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'suppliers.delete',
            'suppliers.restore',
            'business_partners.view',
            'business_partners.create',
            'business_partners.update',
            'business_partners.delete',
            'business_partners.restore',
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'categories.restore',
            'brands.view',
            'brands.create',
            'brands.update',
            'brands.delete',
            'brands.restore',
            'units.view',
            'units.create',
            'units.update',
            'units.delete',
            'units.restore',
            'products.view',
            'products.create',
            'products.update',
            'products.delete',
            'products.restore',
            'price_lists.view',
            'price_lists.create',
            'price_lists.update',
            'price_lists.delete',
            'price_lists.restore',
            'price_list_items.view',
            'price_list_items.create',
            'price_list_items.update',
            'price_list_items.delete',
            'quotations.view',
            'quotations.create',
            'quotations.update',
            'quotations.delete',
            'quotations.restore',
            'sales_orders.view',
            'sales_orders.create',
            'sales_orders.update',
            'sales_orders.delete',
            'sales_orders.restore',
            'inventory.view',
            'inventory.adjust',
            'warehouses.view',
            'warehouses.create',
            'warehouses.update',
            'warehouses.delete',
            'warehouses.restore',
            'inventory_movements.view',
            'inventory_movements.create',
            'inventory_movements.update',
            'inventory_movements.delete',
            'inventory_movements.restore',
            'inventory_movements.void',
            'sales.view',
            'sales.create',
            'sales.cancel',
            'pos.open_shift',
            'pos.close_shift',
            'pos.refund',
            'pos.discount',
            'pos.reprint',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'invoices.send',
            'invoices.void',
            'credit_notes.view',
            'credit_notes.create',
            'credit_notes.update',
            'credit_notes.delete',
            'credit_notes.restore',
            'debit_notes.view',
            'debit_notes.create',
            'debit_notes.update',
            'debit_notes.delete',
            'debit_notes.restore',
            'establishments.view',
            'establishments.create',
            'establishments.update',
            'establishments.delete',
            'establishments.restore',
            'emission_points.view',
            'emission_points.create',
            'emission_points.update',
            'emission_points.delete',
            'emission_points.restore',
            'collections.view',
            'collections.create',
            'collections.update',
            'collections.delete',
            'collections.restore',
            'reports.view',
            'finance.view',
            'finance.manage',
            'accounting.view',
            'accounting.manage',
            'taxes.view',
            'taxes.create',
            'taxes.update',
            'taxes.delete',
            'taxes.restore',
            'payroll.view',
            'payroll.manage',
            'settings.view',
            'settings.manage',
            'withholdings.view',
            'withholdings.create',
            'withholdings.update',
            'withholdings.delete',
            'withholdings.restore',
            'withholdings.send',
            'delivery_guides.view',
            'delivery_guides.create',
            'delivery_guides.update',
            'delivery_guides.delete',
            'delivery_guides.restore',
            'delivery_guides.send',
            'purchase_settlements.view',
            'purchase_settlements.create',
            'purchase_settlements.update',
            'purchase_settlements.delete',
            'purchase_settlements.restore',
            'purchase_settlements.send',
            'tax_definitions.view',
            'tax_definitions.create',
            'tax_definitions.update',
            'tax_definitions.delete',
            'tax_definitions.restore',
            'tax_rules.view',
            'tax_rules.create',
            'tax_rules.update',
            'tax_rules.delete',
            'tax_catalogs.view',
            'tax_catalogs.create',
            'tax_catalogs.update',
            'tax_catalogs.delete',
            'tax_applications.view',
            'sri_catalogs.view',
            'sri_catalogs.create',
            'sri_catalogs.update',
            'sri_catalogs.delete',
            'fiscal_periods.manage',
            'fiscal_periods.close',
            'inventory_document_types.view',
            'inventory_document_types.create',
            'inventory_document_types.update',
            'inventory_document_types.delete',
            'inventory_document_types.restore',
            'lots.view',
            'lots.create',
            'lots.update',
            'lots.delete',
            'lots.restore',
            'serial_numbers.view',
            'serial_numbers.create',
            'serial_numbers.update',
            'serial_numbers.delete',
            'serial_numbers.restore',
            'inventory_balances.view',
            'inventory_balances.create',
            'inventory_balances.update',
            'inventory_balances.delete',
            'inventory_balances.restore',
            'document_types.view',
            'document_types.create',
            'document_types.update',
            'document_types.delete',
            'document_types.restore',
            'chart_of_accounts.view',
            'chart_of_accounts.create',
            'chart_of_accounts.update',
            'chart_of_accounts.delete',
            'chart_of_accounts.restore',
            'journal_entries.view',
            'journal_entries.create',
            'journal_entries.update',
            'journal_entries.delete',
            'journal_entries.restore',
            'journal_entries.approve',
            'journal_entries.void',
        ];

        foreach ($permissions as $permissionName) {
            $permission = Permission::findOrCreate($permissionName, 'web');

            $this->tallyModelChange($permission, $created, $updated);
        }

        $this->reportCreatedAndUpdated($created, $updated);
    }
}
